### ISSUE TITLE
目前脚本发现的问题

### ISSUE THREAD

**Issue by xiaoke777** [1061700625/xyzw_helper#7]
罐子识别不到，答题退不出来，任务周活跃的全部领取一直点击，好友里的一键领取和赠送识别不到

**Comment by 1061700625** [comment]
修改分辨率1280x720,320dpi。如果直接在真机上运行，由于分辨率差异可能会导致以上问题。如果改不了，可以装光速虚拟机。如果有电脑，就装夜神模拟器。
